services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wab
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  verdaccio:
    image: us-central1-docker.pkg.dev/registries-442916/plasmic-prod-us-central1/verdaccio:verdaccio
    environment:
      VERDACCIO_PORT: "4873"
    ports:
      - 4873:4873
    volumes:
      - ./verdaccio-config.yaml:/verdaccio/conf/config.yaml

volumes:
  postgres_data:
