packages:
  - packages/auth-api
  - packages/auth-react
  - packages/cli
  - packages/code-merger
  - packages/create-plasmic-app
  - packages/data-sources
  - packages/data-sources-context
  - packages/host
  - packages/loader-core
  - packages/loader-edge
  - packages/loader-fetcher
  - packages/loader-gatsby
  - packages/loader-nextjs
  - packages/loader-react
  - packages/loader-splits
  - packages/loader-svelte
  - packages/loader-vue
  - packages/nextjs-app-router
  - packages/prepass
  - packages/query
  - packages/react-web
  - packages/react-web-runtime
  - packages/watcher
  - plasmicpkgs/airtable
  - plasmicpkgs/antd
  - plasmicpkgs/antd5
  - plasmicpkgs/chakra-ui
  - plasmicpkgs/framer-motion
  - plasmicpkgs/keen-slider
  - plasmicpkgs/plasmic-basic-components
  - plasmicpkgs/plasmic-embed-css
  - plasmicpkgs/plasmic-nav
  - plasmicpkgs/plasmic-query
  - plasmicpkgs/plasmic-rich-components
  - plasmicpkgs/plasmic-tabs
  - plasmicpkgs/suinova-nft-builder
  - plasmicpkgs/react-aria
  - plasmicpkgs/react-chartjs-2
  - plasmicpkgs/plasmic-link-preview
  - plasmicpkgs/react-slick
  - plasmicpkgs/react-twitter-widgets
  - platform/canvas-packages
  - platform/canvas-packages/internal_pkgs/react-slick
  - platform/host-test
  - platform/integration-tests
  - platform/live-frame
  - platform/loader-html-hydrate
  - platform/loader-tests
  - platform/react-web-bundle
  - platform/sub
  # wab still performs a postinstall patch-package which isn't kosher with pnpm. But can look into pnpm patch.
  # - platform/loader-bundle-env
#  - platform/wab
#  - platform/wab/create-react-app-new/packages/*
